-- This script is executed in tests after Hibernate creates the schema.
-- Use it to fix/override constraints generated by Hibernate if needed.

-- Example: ensure email is unique (Postgres syntax)
-- ALTER TABLE authors ADD CONSTRAINT uq_authors_email UNIQUE (email);

