spring:
  application:
    name: jpa-testcontainer
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
